### ISSUE TITLE
pygemini errors when compiling gemci

### ISSUE THREAD

**Issue by mattzett** [gemini3d/gemci#8]
-- HWM14 not enabled, disabling mini2dns_hwm14_fang
CMake Error at CMakeLists.txt:117 (model_setup):
  model_setup Function invoked with incorrect arguments for function named:
  model_setup

CMake Error at CMakeLists.txt:120 (compare_download):
  compare_download Function invoked with incorrect arguments for function
  named: compare_download

CMake Error at CMakeLists.txt:122 (compare_input):
  compare_input Function invoked with incorrect arguments for function named:
  compare_input

CMake Error at CMakeLists.txt:143 (compare_output):
  compare_output Function invoked with incorrect arguments for function
  named: compare_output

**Comment by scivision** [comment]
fixed by [46c3498](https://github.com/gemini3d/gemci/commit/46c3498e748b4e7750aab30c5ac60c380610d1bf)
